# Generated by Django 2.2.5 on 2021-07-10 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('live', 'Live'), ('finished', 'Finished'), ('yet_to_go', 'Yet to Go'), ('yet_to_go', 'Yet to Go'), ('canceled', 'Canceled')], max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('participation', models.IntegerField()),
                ('status', models.CharField(choices=[('extra', 'Extra'), ('squad', 'Squad')], max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('win_count', models.IntegerField()),
                ('lost_count', models.IntegerField()),
                ('draw_count', models.IntegerField()),
                ('avg_score', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='basketballs.Team')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('goal', 'Goal'), ('assist', 'Assist'), ('block', 'Block')], max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketballs.Match')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketballs.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team', to='basketballs.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=100)),
                ('score', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketballs.Match')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketballs.Team')),
            ],
        ),
    ]
