# Generated by Django 2.2.5 on 2021-07-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketballs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('finished', 'Finished'), ('yet_to_go', 'Yet to Go'), ('canceled', 'Canceled')], max_length=100),
        ),
    ]
