# Generated by Django 2.2.5 on 2021-07-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketballs', '0002_auto_20210710_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpoint',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
