# Generated by Django 2.2.5 on 2021-07-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketballs', '0003_playerpoint_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpoint',
            name='type',
        ),
    ]
